version: '3'
services:
  db:
    container_name: pg_graphql_db
    build:
        context: .
        dockerfile: ./dockerfiles/db/Dockerfile
    volumes:
        - ./dockerfiles/db/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    ports:
      - 5404:5432
    command:
      - postgres
      - -c
      - wal_level=logical
      - -c
      - shared_preload_libraries=pg_stat_statements
    healthcheck:
      test: ["CMD-SHELL", "PGUSER=postgres", "pg_isready"]
      interval: 1s
      timeout: 10s
      retries: 5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gqldb

  rest:
    container_name: pg_graphql_rest
    build:
        context: ./dockerfiles/rest
    restart: always
    ports:
      - 3000:8000
    depends_on:
      - db
    environment:
      DB_URI: postgres://postgres:password@db:5432/gqldb

  graphiql:
    container_name: graphiql
    build:
        context: ./dockerfiles/graphiql
    ports:
        - 4000:8000
    depends_on:
      - db
      - rest
